import 'question_weight_models.dart';

/// Weight mappings for Cognitive Ability Test
/// Maps 60 questions to psychological scales from hierarchical_scales.dart
///
/// Test structure:
/// - Questions 1-20: Logical Reasoning
/// - Questions 21-40: Numerical Ability
/// - Questions 41-60: Verbal Ability
///
/// Scoring: Binary (0 = incorrect, 1 = correct)
/// maxQuestionScore: 1
class CognitiveAbilityWeights {
  static final Map<String, QuestionWeight> weights = {
    // ============================================
    // SECTION 1: LOGICAL REASONING (Questions 1-20)
    // ============================================

    // Q1: Продолжите последовательность: 2, 4, 8, 16, ?
    'cognitive_ability_v1:q1': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q1',
      axisWeights: {
        'analytical_thinking': 1.0,
        'abstract_reasoning': 1.0,
        'problem_solving': 0.8,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.7,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    // Q2: Если все A — это B, и все B — это C, то:
    'cognitive_ability_v1:q2': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q2',
      axisWeights: {
        'analytical_thinking': 1.0,
        'abstract_reasoning': 1.0,
        'problem_solving': 0.8,
        'critical_thinking': 0.9,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    // Q3: Найдите лишнее: Собака, Кошка, Корова, Стул
    'cognitive_ability_v1:q3': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q3',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.8,
        'problem_solving': 0.7,
        'critical_thinking': 0.8,
        'learning_ability': 0.6,
        'attention_control': 0.6,
        'cognitive_flexibility': 0.7,
        'working_memory': 0.5,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.4,
        'thinking_pole': 0.5,
      },
    ),

    // Q4: Продолжите: Z, Y, X, W, ?
    'cognitive_ability_v1:q4': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q4',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.9,
        'problem_solving': 0.7,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.6,
        'cognitive_flexibility': 0.5,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.5,
      },
    ),

    // Q5: Если книга стоит 120 рублей, и цена снизилась на 25%
    'cognitive_ability_v1:q5': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q5',
      axisWeights: {
        'analytical_thinking': 0.8,
        'abstract_reasoning': 0.6,
        'problem_solving': 0.9,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.7,
        'cognitive_flexibility': 0.5,
        'working_memory': 0.8,
        'numerical_ability': 0.9,
        'openness': 0.2,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    // Q6: Аналогия: Рука относится к Перчатке, как Нога относится к ?
    'cognitive_ability_v1:q6': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q6',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.9,
        'problem_solving': 0.7,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'working_memory': 0.5,
        'verbal_intelligence': 0.6,
        'openness': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.5,
      },
    ),

    // Q7: Продолжите последовательность: 1, 1, 2, 3, 5, 8, ?
    'cognitive_ability_v1:q7': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q7',
      axisWeights: {
        'analytical_thinking': 1.0,
        'abstract_reasoning': 1.0,
        'problem_solving': 0.9,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.6,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.8,
        'openness': 0.3,
        'achievement_orientation': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.6,
        'thinking_pole': 0.6,
      },
    ),

    // Q8-Q20: Remaining logical reasoning questions
    'cognitive_ability_v1:q8': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q8',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.8,
        'problem_solving': 0.8,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q9': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q9',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.9,
        'problem_solving': 0.8,
        'critical_thinking': 0.8,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q10': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q10',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.8,
        'problem_solving': 0.8,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.6,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.7,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q11': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q11',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.8,
        'problem_solving': 0.8,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q12': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q12',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.9,
        'problem_solving': 0.8,
        'critical_thinking': 0.8,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.7,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q13': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q13',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.8,
        'problem_solving': 0.8,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q14': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q14',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.9,
        'problem_solving': 0.8,
        'critical_thinking': 0.8,
        'learning_ability': 0.6,
        'attention_control': 0.6,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.7,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q15': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q15',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.8,
        'problem_solving': 0.8,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q16': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q16',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.8,
        'problem_solving': 0.8,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q17': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q17',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.9,
        'problem_solving': 0.8,
        'critical_thinking': 0.8,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.7,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q18': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q18',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.8,
        'problem_solving': 0.8,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.6,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q19': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q19',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.9,
        'problem_solving': 0.8,
        'critical_thinking': 0.8,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.7,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    'cognitive_ability_v1:q20': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q20',
      axisWeights: {
        'analytical_thinking': 0.9,
        'abstract_reasoning': 0.8,
        'problem_solving': 0.8,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.6,
        'working_memory': 0.6,
        'openness': 0.3,
        'achievement_orientation': 0.4,
        'intellectual_curiosity': 0.5,
        'intuition_pole': 0.5,
        'thinking_pole': 0.6,
      },
    ),

    // ============================================
    // SECTION 2: NUMERICAL ABILITY (Questions 21-40)
    // ============================================

    'cognitive_ability_v1:q21': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q21',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q22': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q22',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q23': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q23',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.8,
        'problem_solving': 0.9,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.7,
        'working_memory': 0.8,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q24': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q24',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q25': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q25',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.8,
        'problem_solving': 0.9,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.7,
        'working_memory': 0.8,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q26': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q26',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q27': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q27',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q28': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q28',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.8,
        'problem_solving': 0.9,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.7,
        'working_memory': 0.8,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q29': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q29',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q30': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q30',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.8,
        'problem_solving': 0.9,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.7,
        'working_memory': 0.8,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q31': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q31',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q32': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q32',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q33': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q33',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.8,
        'problem_solving': 0.9,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.7,
        'working_memory': 0.8,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q34': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q34',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q35': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q35',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.8,
        'problem_solving': 0.9,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.7,
        'working_memory': 0.8,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q36': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q36',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q37': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q37',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q38': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q38',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.8,
        'problem_solving': 0.9,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.7,
        'working_memory': 0.8,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q39': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q39',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.9,
        'critical_thinking': 0.6,
        'learning_ability': 0.6,
        'attention_control': 0.8,
        'working_memory': 0.9,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    'cognitive_ability_v1:q40': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q40',
      axisWeights: {
        'numerical_ability': 1.0,
        'analytical_thinking': 0.8,
        'problem_solving': 0.9,
        'critical_thinking': 0.7,
        'learning_ability': 0.6,
        'attention_control': 0.7,
        'working_memory': 0.8,
        'conscientiousness': 0.4,
        'achievement_orientation': 0.5,
        'thinking_pole': 0.7,
      },
    ),

    // ============================================
    // SECTION 3: VERBAL ABILITY (Questions 41-60)
    // ============================================

    'cognitive_ability_v1:q41': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q41',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q42': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q42',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q43': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q43',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.5,
        'critical_thinking': 0.8,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.7,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q44': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q44',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q45': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q45',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.5,
        'critical_thinking': 0.8,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.7,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q46': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q46',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q47': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q47',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q48': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q48',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.5,
        'critical_thinking': 0.8,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.7,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q49': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q49',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q50': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q50',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.5,
        'critical_thinking': 0.8,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.7,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q51': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q51',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q52': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q52',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q53': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q53',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.5,
        'critical_thinking': 0.8,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.7,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q54': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q54',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q55': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q55',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.5,
        'critical_thinking': 0.8,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.7,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q56': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q56',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q57': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q57',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q58': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q58',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.5,
        'critical_thinking': 0.8,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.7,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q59': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q59',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.6,
        'problem_solving': 0.5,
        'critical_thinking': 0.7,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.8,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),

    'cognitive_ability_v1:q60': const QuestionWeight(
      testId: 'cognitive_ability_v1',
      questionId: 'q60',
      axisWeights: {
        'verbal_intelligence': 1.0,
        'analytical_thinking': 0.7,
        'problem_solving': 0.5,
        'critical_thinking': 0.8,
        'learning_ability': 0.7,
        'attention_control': 0.5,
        'cognitive_flexibility': 0.7,
        'openness': 0.5,
        'intellectual_curiosity': 0.6,
        'intuition_pole': 0.4,
      },
    ),
  };
}
